ninshirts/urls.py
from django.conf.urls import patterns, include, url
from ninshirts import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'apps.catalog.views.index'),
    url(r'^admin/', include(admin.site.urls)),

    # Uncomment the next two line if running the development server:
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}),

    url(r'^(?P<category_tag>[a-z0-9-]+)/$',
        'apps.catalog.views.category'),
    url(r'^(?P<category_tag>[a-z0-9-]+)/(?P<product_tag>[a-z0-9-]+)/$',
        'apps.catalog.views.product'),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
)

apps/catalog/models.py
from django.db import models
from itertools import chain
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill

class Category(models.Model):
    parent = models.ForeignKey('Category', null=True)
    name = models.CharField(max_length=200)
    tag = models.CharField(max_length=200)
    left_id = models.IntegerField()
    right_id = models.IntegerField()

    class Meta:
        ordering = ['left_id']
        verbose_name_plural = 'categories'

    def __unicode__(self):
        return self.name

    def products(self):
        """
        Returns a flat list of all products that fall within a category and
        it's children.
        """
        children = Category.objects.filter(left_id__gt=self.left_id,
                                           right_id__lt=self.right_id)
        products = [self.product_set.all()]
        for child in children:
            products.append(child.product_set.all())

        return set(chain.from_iterable(products))

    def depth(self):
        """
        Returns the depth of a category in the category hierarchy.
        """
        depth = 1
        parent = self.parent
        while parent is not None:
            depth += 1
            parent = parent.parent

        return depth

    def family(self):
        """
        Returns a flat list of the immediate children, siblings, and ancestors
        of a category.
        """

        # add children
        family = list(Category.objects.filter(parent__exact=self))
        if self.parent is None:
            family += list(Category.objects.filter(parent__exact=None))
        else:
            parent = self.parent
            while parent is not None:
                # add siblings
                family += list(Category.objects.filter(parent__exact=parent))
                # add parent
                family.append(parent)
                parent = parent.parent

        return set(family)


class OptionType(models.Model):
    name = models.CharField(max_length=200)

    def __unicode__(self):
        return self.name


class Option(models.Model):
    option_type = models.ForeignKey(OptionType)
    name = models.CharField(max_length=200)
    abbreviation = models.CharField(max_length=10)

    def __unicode__(self):
        return "[%s] %s" % (self.option_type.name, self.name)

    def type(self):
        return self.option_type.name

    

class Product(models.Model):
    categories = models.ManyToManyField(Category)
    name = models.CharField(max_length=200)
    tag = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    options = models.ManyToManyField(Option)

    def __unicode__(self):
        return self.name

    def deep_categories(self):
        """
        Returns a flat list of all the product's categories and ancestors.
        """
        categories = list(self.categories.all())
        for category in self.categories.all():
            parent = category.parent
            while parent:
                categories.append(parent)
                parent = parent.parent

        return categories

class ProductImage(models.Model):
    product = models.ForeignKey(Product)
    original = models.ImageField(upload_to='products')
    zoom = ImageSpecField([ResizeToFill(500,500)], format='PNG',
        image_field='original')
    thumbnail = ImageSpecField([ResizeToFill(200,200)], format='PNG',
        image_field='original')
    thumbnail_medium = ImageSpecField([ResizeToFill(100,100)], format='PNG',
        image_field='original')
    thumbnail_tiny = ImageSpecField([ResizeToFill(50,50)], format='PNG',
        image_field='original')

    class Meta:
        order_with_respect_to = 'product'

    def __unicode__(self):
        return "%s [%d]" % (self.product.name, self._order)

apps/catalog/views.py
from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext
from django.http import Http404
from apps.catalog.models import Category, Product, ProductImage

def index(request):
    categories = Category.objects.all()
    return render_to_response('catalog/index.html',
        {'categories': categories}, context_instance=RequestContext(request))

def category(request, category_tag):
    category = get_object_or_404(Category.objects.all(), tag=category_tag)
    return render_to_response('catalog/category.html',
        {'category': category}, context_instance=RequestContext(request))

def product(request, category_tag, product_tag):
    category = get_object_or_404(Category.objects.all(), tag=category_tag)
    product = get_object_or_404(Product.objects.all(), tag=product_tag)
    if category in product.deep_categories():
        images = ProductImage.objects.filter(
            pk__in=product.get_productimage_order())
        # force caching of zoom spec if needed
        for image in images:
            url = image.zoom.url
        return render_to_response('catalog/product.html',
            {'product': product, 'images': images},
            context_instance=RequestContext(request))
    else:
        raise Http404

catalog/views.py
from django.shortcuts import render_to_response, get_object_or_404
from django.http import Http404
from catalog.models import Category, Product

def index(request):
    categories = Category.objects.all()
    return render_to_response('catalog/index.html', {'categories': categories})

def category(request, category_tag):
    category = get_object_or_404(Category.objects.all(), tag=category_tag)
    return render_to_response('catalog/category.html', {'category': category})

def product(request, category_tag, product_tag):
    category = get_object_or_404(Category.objects.all(), tag=category_tag)
    product = get_object_or_404(Product.objects.all(), tag=product_tag)
    if category in product.deep_categories():
        return render_to_response('catalog/product.html', {'product': product})
    else:
        raise Http404

ninshirts/templates/catalog/base.html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <title>{% block title %}ninshirts.com{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="/static/css/reset.css" />
    <link rel="stylesheet" type="text/css" href="/static/css/text.css" />
    <link rel="stylesheet" type="text/css" href="/static/css/960.css" />
    <link rel="stylesheet" type="text/css" href="/static/css/catalog.css" />
    <script src="http://use.edgefonts.net/maven-pro.js"></script> 
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.1/jquery.min.js"></script>
    <script type="text/javascript">

      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-763021-25']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

    </script>
</head>
<body>
<div class="container_12">
<div id="header">
<h1 id="siteTitle"><a href="/">ninshirts.com</a></h1>
<div id="top_nav">
{% include "catalog/topnav.html" %}
</div>
</div>
<div id="side_nav">
<div class="grid_3">
{% include "catalog/sidenav.html" %}
</div>
</div>
<div class="grid_9">
<div class="grid_9">
{% block banner %}{% endblock %}
</div>
<div class="grid_9">
{% block content %}{% endblock %}
</div>
</div>
<div class="clear"></div>
<div class="grid_12" id="footer">

    <ul>
        <li><a href="http://www.theninhotline.net">nin hotline</a></li>
        <li><a href="http://www.ninwiki.com">nin wiki</a></li>
        <li><a href="http://www.nincatalog.com">nin catalog</a></li>
        <li><a href="http://www.nintourhistory.com">nin tour history</a></li>
        <li class="last"><a href="http://www.nin.com">nin.com</a></li>
    </ul>
    <p><a href="mailto:contact@ninshirts.com">contact@ninshirts.com</a></p>

</div>
</div>
</body>
</html>

ninshirts/templates/catalog/category.html
{% extends 'catalog/base.html' %}

{% block title %}nin shirts > {{ category.name }}{% endblock %}
{% block banner %}<h2>{{ category.name }}</h2>{% endblock %}
{% block content %}
<script type="text/javascript">
    $(document).ready(function(){
        $('.browseImage').hover(function() {
             var $this = $(this);
             $this.next().fadeIn();
        },
        function() {
             var $this = $(this);
             $this.next().fadeOut();
        })
    });
</script>
<!---<div class="prefix_5 grid_4"><p>Pagination and filters</p></div>--->
<div id="products">
{% for product in category.products|dictsortreversed:"id" %}
{% if forloop.counter0|divisibleby:"3" %}
{% endif %}
<div class="grid_3{% if forloop.counter0|divisibleby:"3" %} alpha{% endif %}{% if forloop.counter0|add:"-2"|divisibleby:"3" %} omega{% endif %} productContainer">
    <a href="{% url apps.catalog.views.product category.tag product.tag %}">
        <img class="browseImage" src="{{ product.productimage_set.all.0.thumbnail.url }}" alt="{{product.name}}"/>
        <div class="title">{{product.name}}</div>
    </a>
</div>
{% endfor %}
</div>

{% comment %}
<div class="alpha grid_3"><p>img</p></div>
<div class="grid_3 omega"><p>img</p></div>
{% block content %}
<div class="grid_16">
<p><a href="{% url ninshirts.catalog.views.index %}">ninshirts.com</a></p>
</div>
<div class="clear"></div>
{% for product in category.product_set.all %}
<div class="grid_3{% if forloop.first %} prefix_5{% endif %}{% if forloop.last %} suffix_5{% endif %}">
<p><a href="{% url ninshirts.catalog.views.product category.tag product.tag %}">{{ product.name }}</a></p>
</div>
{% endfor %}
{% endcomment %}
{% endblock %}

ninshirts/templates/catalog/index.html
{% extends 'catalog/base.html' %}

{% block banner %}<h2>Merch</h2>{% endblock %}
{% block content %}
<div style="font-size:12pt;font-weight:bold;">
<p>Welcome to ninshirts.com! This is ninshirts.com! At ninshirts.com, anything is possible!</p>
<p>This is a fan project to catalog officially licensed Nine Inch Nails t-shirts and merchandise.</p>
</div>
{% endblock %}

ninshirts/templates/catalog/product.html
{% extends 'catalog/base.html' %}

{% block title %}nin shirts > {{ product.name }}{% endblock %}
{% block content %}
<script type="text/javascript">
    $(document).ready(function(){
        $('.productThumb').click(function(e) {
            e.preventDefault();
            var $this = $(this);
            link = $this.attr('href');
            $("#detailImage").attr('src', link);
            $("#zoomLink").attr('href',link.replace('thumbnail','zoom'));
        })
		$("#zoomLink").click(function(e){
			e.preventDefault();
			var $this = $(this);
			link = $this.attr('href');
			$("#zoomImage").attr('src',link);
			$("#imageZoom").fadeIn(300);
			return false;
		});
		
		$('#closeButton').click(function(){
			$("#imageZoom").fadeOut(400);
		})
		
    });
</script>
<div id="imageContainer">
    <div>
        <a href="{{ images.0.zoom.url }}" id="zoomLink"><img id="detailImage" src="{{ images.0.thumbnail.url }}" alt="{{ product.name }}" /></a>
    </div>
    {% if images|length > 1 %}
    <div id="imageViews">
        {% comment %}
        <!-- I would like to process images upon upload, creating several size images - detail, zoom, and thumbnail.
        Anchor tags below would be to detail, img tags use thumbnail.
        Javascript would load the detail upon clicking the thumbnail. Rather than just front and back, a 'view' system might be nice - views a,b,c, etc.-->
        {% endcomment %}
        <ul>
            {% for image in images %}
            <li><a href="{{ image.thumbnail.url }}" class="productThumb"><img src="{{ image.thumbnail_medium.url }}" alt="{{ product.name }}" /></a></li>
            {% endfor %}
        </ul>
    </div>
    {% endif %}
</div>
<div id="productDetail">
    <h2>{{ product.name }}</h2>
    <div id="productDescription">
    
        {% for option in product.options.all %}
            {% if option.type == "Color" %}{{ option.name }}{% endif %}
        {% endfor %}
        {% comment %}
        <!-- Rather than have t-shirt,hoodie,litho, etc. as a category, I would like to set those up as a 'productType' -->
        {% for category in product.categories.all %}{% if category == "Men's" or "Women's" %}{{ category }} {% endif %}{% endfor %} 
        {% endcomment %}
        {{ product.description }} 
    </div>
    <div id="relations">
        Related Categories: {{ product.categories.all|join:', ' }}
    </div>
</div>
<div id="imageZoom">
	<img src="{{images.0.zoom.url}}" id="zoomImage" alt="{{product.name}}" />
	<div id="closeButton">close</div>
</div>
{% endblock %}


ninshirts/templates/catalog/sidenav.html
<ul id="sideNav">
{% for navcategory in sidenav_categories %}
    <li class="l{{ navcategory.depth }}{% if navcategory.id == category.id %} active{% endif %}"><a href="/{{ navcategory.tag }}">{{ navcategory.name }}</a></li>
{% endfor %}
</ul>

ninshirts/templates/catalog/topnav.html
<div id="topNav">
    <ul>
        <li><a href="/apparel/">Apparel</a></li>
        <li><a href="/accessories/">Accessories</a></li>
        <li><a href="/tours/">Tours</a></li>
        <li><a href="/records/">Records</a></li>
        <li><a href="/htda/">HTDA</a></li>
    </ul>
</div>

templates/catalog/category.html
{% extends 'catalog/base.html' %}


{% block banner %}<h2>{{ category.name }}</h2>{% endblock %}
{% block content %}
<div class="prefix_5 grid_4"><p>Pagination and filters</p></div>
<div id="products">
{% for product in category.products %}
{% if forloop.counter0|divisibleby:"3" %}
<div class="grid_9">&nbsp;</div>
{% endif %}
<div class="grid_3{% if forloop.counter0|divisibleby:"3" %} alpha{% endif %}{% if forloop.counter0|add:"-2"|divisibleby:"3" %} omega{% endif %}">
    <a href="{% url ninshirts.catalog.views.product category.tag product.tag %}">
        <img width="200" height="200" src="/static/img/{{ product.front.url }}"/>
    </a>
</div>
{% endfor %}
</div>

{% comment %}
<div class="alpha grid_3"><p>img</p></div>
<div class="grid_3 omega"><p>img</p></div>
{% block content %}
<div class="grid_16">
<p><a href="{% url ninshirts.catalog.views.index %}">ninshirts.com</a></p>
</div>
<div class="clear"></div>
{% for product in category.product_set.all %}
<div class="grid_3{% if forloop.first %} prefix_5{% endif %}{% if forloop.last %} suffix_5{% endif %}">
<p><a href="{% url ninshirts.catalog.views.product category.tag product.tag %}">{{ product.name }}</a></p>
</div>
{% endfor %}
{% endcomment %}
{% endblock %}

templates/catalog/collection.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="grid_16">
<p><a href="{% url ninshirts.catalog.views.index %}">ninshirts.com</a></p>
</div>
<div class="clear"></div>
{% for shirt in collection.shirt_set.all %}
<div class="grid_3{% if forloop.first %} prefix_5{% endif %}{% if forloop.last %} suffix_5{% endif %}">
<p><a href="{% url ninshirts.catalog.views.shirt collection.tag shirt.tag %}">{{ shirt.name }}</a></p>
</div>
{% endfor %}
{% endblock %}

templates/catalog/sidenav.html
<ul>
  <li class="l1"><a href="/apparel/">Apparel</a></li>
    <li class="l2"><a href="/shirts/">Shirts</a></li>
      <li class="l3"><a href="/t-shirts/">T-Shirts</a></li>
      <li class="l3"><a href="/hoodies/">Hoodies</a></li>
      <li class="l3"><a href="/long-sleeve-shirts/">Long Sleeve Shirts</a></li>
    <li class="l2"><a href="/mens/">Men's</a></li>
    <li class="l2"><a href="/womens/">Women's</a></li>
  <li class="l1"><a href="/posters/">Posters</a></li>
  <li class="l1"><a href="/tours/">Tours</a></li>
    <li class="l2"><a href="/live-with-teeth-tour/">Live: With Teeth</a></li>
      <li class="l3"><a href="/live-with-teeth-summer-amphitheater-tour/">Summer Amphitheater Tour</a></li>
  <li class="l1"><a href="/records/">Records</a></li>
    <li class="l2"><a href="/pretty-hate-machine/">Pretty Hate Machine</a></li>
    <li class="l2"><a href="/broken/">Broken</a></li>
    <li class="l2"><a href="/the-downward-spiral/">The Downward Spiral</a></li>
    <li class="l2"><a href="/with-teeth/">With Teeth</a></li>
    <li class="l2"><a href="/year-zero/">Year Zero</a></li>
    <li class="l2"><a href="/ghosts-i-iv/">Ghosts I-IV</a></li>
    <li class="l2"><a href="/the-slip/">The Slip</a></li>
  <li class="l1"><a href="/venues/">Venues</a></li>
    <li class="l2"><a href="/boston/">Boston</a></li>
    <li class="l2"><a href="/chicago/">Chicago</a></li>
</ul>